Add fetchSize / batchSize to Import and export with GeoPackage
claeis/iox-wkf pull request #49
Opened 2023-06-14 12:35 UTC by patrickackermann

2023-06-14 13:58 UTC, Philippluca requested changes

2023-06-14 13:58 UTC, Philippluca commented on src/main/java/ch/interlis/ioxwkf/dbtools/AbstractExportFromdb.java
> +				while (rs.next()) {
Q: Müsste es hier nicht rs.hasNext() sein?

2023-06-14 13:58 UTC, Philippluca commented on src/main/java/ch/interlis/ioxwkf/gpkg/GeoPackageWriter.java
> +                    // A .gpkg-journal file will be around. Rollback/Close does not help.
REQ: Hier gibt es noch ein TODO.

2023-06-14 13:58 UTC, Philippluca commented on src/main/java/ch/interlis/ioxwkf/gpkg/GeoPackageWriter.java
> +                currentBatchSize = 0;
Q: Müssen wir hier finally -> try -> throw verwenden? Das pattern fühlt sich irgendwie falsch an.

2023-06-14 14:55 UTC, patrickackermann commented on src/main/java/ch/interlis/ioxwkf/dbtools/AbstractExportFromdb.java
> +				while (rs.next()) {
Nein, hier wird der Inhalt des ResultSet durchgegangen. [next()](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#next--) bewegt den Crusor eins weiter und returned ob es eine weitere Zeile hat.
[hasNext()](https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#hasNext--) wird benötigt, beim Iterieren durch eine Collection mit einem Iterator.

2023-06-14 14:55 UTC, patrickackermann commented on src/main/java/ch/interlis/ioxwkf/gpkg/GeoPackageWriter.java
> +                    // A .gpkg-journal file will be around. Rollback/Close does not help.
Das TODO war schon vorher da. Ich hatte einfach das Pech, das ich diesen Code verschieben musste.

Das journal File ist das Rollback-Journal, das beim nächsten Verbinden nach einem Crash dazu benötigt wird, um die fehlgeschlagene Transaktion rückgängig zu machen. Siehe auch https://www.sqlite.org/tempfiles.html

Meiner Ansicht nach gibt es hier nichts, was die Applikation noch machen könnte. TODO ersatzlos entfernen?

2023-06-14 14:55 UTC, patrickackermann commented on src/main/java/ch/interlis/ioxwkf/gpkg/GeoPackageWriter.java
> +                currentBatchSize = 0;
Ein try-with-resources wäre besser, lässt sich hier aber nicht einfach nutzen, da das PreparedStatement über mehrere Aufrufe von `GeoPackageWriter.write(IoxEvent event)` genutzt wird. Wenn `PreparedStatement.close()` eine Exception wirft wird das die Exception von `executeBatch` überdecken. Soll ich die mögliche Exception von `close()` einfach ignorieren?

2023-06-16 13:35 UTC, Philippluca approved these changes

2023-06-29 07:52 UTC, claeis commented
Warum wurde ch.ehi.ili2db.base.StatementExecutionHelper nicht benutzt?

2023-06-29 13:46 UTC, patrickackermann commented
> Warum wurde ch.ehi.ili2db.base.StatementExecutionHelper nicht benutzt?

Mir war nicht bewusst, dass es dafür schon eine Hilfsklasse gibt. Ich verwende jetzt `ch.ehi.ili2db.base.StatementExecutionHelper`.

2023-06-29 14:34 UTC, merged